version: "3.9"
services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-fe
    env_file: .env
    ports:
      - "7860:7860"
  api-rest:
    build:
      context: .
      dockerfile: Dockerfile-be
    env_file: .env
    ports:
      - "8000:8000"