version: "3.9"

services:

  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-fe
    env_file: .env
    ports:
      - "7860:7860"

  api-rest:
    build:
      context: .
      dockerfile: Dockerfile-be
    env_file: .env
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data_source.yml:/etc/grafana/provisioning/datasources/data_source.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"