version: "3.9"

services:

  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-fe
    env_file: .env
    ports:
      - "7860:7860"

  api-rest:
    build:
      context: .
      dockerfile: Dockerfile-be
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - loki
      - tempo
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./osservability/prometheus:/etc/prometheus/
      - ./osservability/prometheus/prometheus_data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:1.2.0
    volumes:
      - ./osservability/tempo/tempo.yml:/etc/tempo.yml
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yml" ]
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    volumes:
      - ./osservability/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./osservability/grafana/data_source.yml:/etc/grafana/provisioning/datasources/data_source.yml
      - ./osservability/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./osservability/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"