    FROM python:3.8-slim

WORKDIR dir/

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

COPY requirements_be.txt .

RUN pip install -r ./requirements_be.txt \
    && rm -rf /root/.cache/pip

COPY src/__init__.py src/
COPY src/api/ src/api

RUN apt-get --yes install libsndfile1

COPY setup.py .

RUN pip install .

EXPOSE 8000

ENTRYPOINT ["python3", "src/api/api_rest.py"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]