# config file version
apiVersion: 1

datasources:
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:8080
    version: 1
    editable: false
    uid: tempo
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true