{
 "title": "GTZAN_Music_Genre",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "BE - Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Genre Predicted",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{compose_service=\"api-rest\"} |~ `(blues|classical|country|disco|hiphop|jazz|metal|pop|reggae|rock)`"
    }
   ]
  },
  {
   "title": "Prediction",
   "type": "gauge",
   "description": "Prediction with status 200 OK",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlette_requests_processing_time_seconds_count{method=\"POST\", path_template=\"/predict/music\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest RAM capacity used",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"api-rest:8000\"} / 9.537*10^(-7)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API LOGS",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{compose_service=\"api-rest\"} | logfmt"
    }
   ]
  }
 ]
}